server:
  port: 8081

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3310/SA_Store?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest